// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package server

import (
	"github.com/yuweiweiouo/coding-exercise/internal/config"
	"github.com/yuweiweiouo/coding-exercise/internal/controller"
	"github.com/yuweiweiouo/coding-exercise/internal/db"
	"github.com/yuweiweiouo/coding-exercise/internal/router"
)

// Injectors from wire.go:

func CreateServer(configName string) (*Server, func(), error) {
	configConfig, err := config.New(configName)
	if err != nil {
		return nil, nil, err
	}
	gormDB, err := db.New(configConfig)
	if err != nil {
		return nil, nil, err
	}
	bookController := controller.NewBookController()
	controllers := &controller.Controllers{
		Book: bookController,
	}
	engine := router.New(configConfig, controllers)
	server := New(gormDB, configConfig, engine)
	return server, func() {
	}, nil
}
