// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/yuweiweiouo/coding-exercise/internal/config"
	"github.com/yuweiweiouo/coding-exercise/internal/db"
)

// Injectors from wire.go:

func CreateApp() (*App, func(), error) {
	configConfig, err := config.New()
	if err != nil {
		return nil, nil, err
	}
	gormDB, err := db.New(configConfig)
	if err != nil {
		return nil, nil, err
	}
	app := New(gormDB)
	return app, func() {
	}, nil
}
